version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER_PROD}
      POSTGRES_PASSWORD: ${DB_PASS_PROD}
    ports: 
      - '5432:5432'
    volumes:
      - escola-db:/var/lib/postgresql/data

  escola-crud:
    image: ticocarrilho/escola-crud:latest
    environment:
      DB_NAME_PROD: ${DB_NAME_PROD}
      DB_USER_PROD: ${DB_USER_PROD}
      DB_PASS_PROD: ${DB_PASS_PROD}
      DB_HOST_PROD: ${DB_HOST_PROD}
    depends_on:
      - postgres
    ports:
      - '3001:3001'
        
volumes:
  escola-db: